// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIcnIgnTQ22flDMne4zcQHHlgrt_lGRJQ',
    appId: '1:488019770048:web:a82a0a4a8c322ccd144b25',
    messagingSenderId: '488019770048',
    projectId: 'robby-5d45c',
    authDomain: 'robby-5d45c.firebaseapp.com',
    storageBucket: 'robby-5d45c.appspot.com',
    measurementId: 'G-MFRDLT02FJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXqa18euAZervgpbgHC9UBiCLbvTczFM',
    appId: '1:488019770048:android:418e6d3a81d6d2c1144b25',
    messagingSenderId: '488019770048',
    projectId: 'robby-5d45c',
    storageBucket: 'robby-5d45c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTy0Y00VGqu92WV50tUX_wdb4620z4x00',
    appId: '1:488019770048:ios:16b30862b45f3124144b25',
    messagingSenderId: '488019770048',
    projectId: 'robby-5d45c',
    storageBucket: 'robby-5d45c.appspot.com',
    iosClientId: '488019770048-805cbb8pbe0ad2n4c41cu6qs1f917qj2.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTy0Y00VGqu92WV50tUX_wdb4620z4x00',
    appId: '1:488019770048:ios:5eea3eb891730dfe144b25',
    messagingSenderId: '488019770048',
    projectId: 'robby-5d45c',
    storageBucket: 'robby-5d45c.appspot.com',
    iosClientId: '488019770048-ivq5bnt04h91drev797fksfcvj8r583n.apps.googleusercontent.com',
    iosBundleId: 'com.example.worldTime.RunnerTests',
  );
}
